---
title: CKAN API
author: Alan Yeung
date: '2019-05-27'
slug: ckan-api
categories:
  - R
tags:
  - R
  - open-data
image:
  caption: ''
  focal_point: ''
draft: TRUE
---

I've already got lots of rough pieces of R code written as I've been exploring/testing various things in the past. A lot of this is currently stored in a pretty disorganised fashion so I think it might be a good idea to start writing some of these up into blog posts -- at the very least, this should make it easier for me to find things later! To start with, I am writing a short post here about how to download data from the CKAN API directly into R -- [CKAN](https://ckan.org) is an open source data portal platform (basically a tool for making open data websites) and the reason I became interested in it is because this is the platform that [NHS Scotland has chosen to host their open data](https://www.opendata.nhs.scot).  
  
It is becoming increasingly important for public sector organisations to make their data open. In Scotland, this is clear from the [Scottish Government's open data strategy](https://www.gov.scot/publications/open-data-strategy). They believe that providing open data not only aids transparency, but should also result in wider social and economic benefits in the long run. My opinion generally matches this but I feel that one thing to be wary of is the potential for users to interpret data incorrectly so therefore it is absolutely crucial to provide as much information as possible about the datasets. On balance, the upsides of providing open data should definitely outweigh the downsides, particularly if pragmatic steps are taken to mitigate potential issues around using the data incorrectly or producing misleading analyses.  
  
Much work needs to be done. The level of open data provision by organisations in Scotland is currently lagging behind other parts of the UK but encouragingly, the situation is improving (see [this blog post by Ian Watt](https://codethecity.co.uk/2019/02/24/scotlands-open-data-february-2019-an-update) for more on this). NHS Scotland has contributed to this improvement by launching their open data platform -- I will simply refer to this as CKAN from hereafter. All of the data held on this platform is licensed under the [UK Open Government Licence (OGL)](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3) (what you can and can't do with the data is well described there in detail but to me, the gist of it seems to be that more or less do what you want with the data as long as you properly acknowledge the source). Each dataset held on CKAN is assigned a *resource ID* which can be found in the 'Additional Information' section once you are on a dataset's page. It is essential to know the resource ID of the dataset you are interested in when you are working with the CKAN API.


